
# This is a basic workflow to help you get started with Actions

name: test pymongo

# Controls when the action will run. 
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '37 11 * * 6'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  scheduled:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
           python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dnspython pymongo
      - name: check pymongo
        run: |
          python
          import pymongo
          client = pymongo.MongoClient('mongodb+srv://JDRanpariya:Jaygurukul@cluster0.lalaj.mongodb.net/nsfw-porn?retryWrites=true&w=majority') 
          db = client.nsfw-porn
          db.name
